#!/usr/bin/env node

/**
 * Build script to convert markdown docs to a JavaScript module
 *
 * Reads all markdown files from /docs/ and generates
 * playground/utils/docs-content.js with pre-rendered HTML.
 *
 * Usage: npm run build:docs
 */

import { promises as fs } from 'fs';
import { join, dirname, basename } from 'path';
import { fileURLToPath } from 'url';
import { marked } from 'marked';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const DOCS_DIR = join(ROOT, 'docs');
const OUTPUT_FILE = join(ROOT, 'playground', 'utils', 'docs-content.js');

// Configure marked for consistent output
marked.setOptions({
  gfm: true,
  breaks: false,
});

// Mapping from markdown filenames to export names
const DOC_FILES = {
  'getting-started.md': 'gettingStarted',
  'syntax.md': 'syntax',
  'stdlib.md': 'stdlib',
  'debug.md': 'debug',
  'cli.md': 'cli',
  'examples.md': 'examples',
};

async function buildDocs() {
  console.log('Building documentation...\n');

  const exports = {};
  const missing = [];

  for (const [filename, exportName] of Object.entries(DOC_FILES)) {
    const filepath = join(DOCS_DIR, filename);

    try {
      const markdown = await fs.readFile(filepath, 'utf-8');
      const html = marked.parse(markdown);
      exports[exportName] = html;
      console.log(`  ✓ ${filename} → ${exportName}`);
    } catch (err) {
      if (err.code === 'ENOENT') {
        missing.push(filename);
        console.log(`  ✗ ${filename} (not found)`);
      } else {
        throw err;
      }
    }
  }

  if (missing.length > 0) {
    console.log(`\nWarning: ${missing.length} documentation file(s) not found.`);
    console.log('Create these files to complete the documentation:');
    missing.forEach(f => console.log(`  - docs/${f}`));
    console.log('');
  }

  // Generate the JavaScript module
  let output = `// Auto-generated by scripts/build-docs.js
// Do not edit manually - edit the markdown files in /docs/ instead

`;

  for (const [name, html] of Object.entries(exports)) {
    // Escape backticks and ${} for template literals
    const escaped = html
      .replace(/\\/g, '\\\\')
      .replace(/`/g, '\\`')
      .replace(/\$\{/g, '\\${');

    output += `export const ${name} = \`${escaped}\`;\n\n`;
  }

  // Add a list of all available content for convenience
  const exportNames = Object.values(DOC_FILES).filter(name => exports[name]);
  output += `// All available documentation sections\n`;
  output += `export const sections = {\n`;
  for (const name of exportNames) {
    output += `  ${name},\n`;
  }
  output += `};\n`;

  await fs.writeFile(OUTPUT_FILE, output);

  console.log(`Generated: playground/utils/docs-content.js`);
  console.log(`Exports: ${Object.keys(exports).join(', ')}`);
}

buildDocs().catch(err => {
  console.error('Build failed:', err);
  process.exit(1);
});
